baseURL = "https://example.com"
languageCode = "en-us"
title = "Retro Web Central - Y2K Compliant Since 1999"
theme = "vintage-web-hugo-theme"

# Pagination
[pagination]
  pagerSize = 10
  path = "page"

# Enable raw HTML for vintage content
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Suppress raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

[[menu.main]]
  name = "Guestbook"
  url = "/guestbook/"
  weight = 40

# Theme Parameters
[params]
  # Site Description
  description = "Your ultimate destination for nostalgic web experiences and retro tech wisdom"
  author = "WebMaster3000"

  # Retro Features
  show_browser_chrome = true
  show_status_bar = true
  show_sidebar = true
  show_welcome_message = true
  welcome_message = "Welcome to the World Wide Web! You are visitor #999,999!"

  # Content Display
  show_featured_sections = true
  show_stats = true
  show_retro_elements = true
  show_sharing = true

  # Footer Options
  show_retro_footer = true
  show_build_info = false

  # Sidebar Options
  show_sidebar_stats = true
  show_retro_sidebar = true
  sidebar_content = "This site is best viewed in Netscape Navigator 4.0 at 1024x768 resolution!"

  # Social Links
  [params.social]
    twitter = "raisingpixels"
    github = "raisingpixels"
    email = "webmaster@example.com"

  # Repository (for edit links)
  repo_url = "https://github.com/raisingpixels/vintage-web-hugo-theme"
  edit_page = true
